version: '3.3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - akatsuki
        volumes:
            - ../:/var/www/html
            - ./nginx/conf:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx/
        depends_on:
            - app
            
    app:
        build: ./php
        container_name: app
        networks:
            - akatsuki
        volumes:
            - ../:/var/www/html
        depends_on:
            - db
        links:
            - db

    db:
        container_name: db
        image: mysql:5.7
        restart: always
        expose:
            - 3306
        ports:
            - "3306:3306"
        networks:
            - akatsuki
        environment:
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root

networks:
    akatsuki:
